# Importar Pandas y verificar versión

In [1]:
import pandas as pd

In [ ]:
print(pd.__version__)

1.5.3

# Series

Una Serie es un arreglo unidimensional capaz de almacenar cualquier tipo de datos. Es similar a una columna en una hoja de cálculo o una lista en Python, pero con capacidades adicionales para análisis de datos

In [ ]:
data = [1, 2, 3, 4]
series = pd.Series(data)
print(series)

0    1
1    2
2    3
3    4
dtype: int64

In [ ]:
indices = ['a', 'b', 'c', 'd']
series = pd.Series(data, index=indices)
print(series)

a    1
b    2
c    3
d    4
dtype: int64

# Dataframes

Un DataFrame es una estructura bidimensional, tamaño mutable, y datos potencialmente heterogéneos. Es similar a una tabla en una base de datos, una hoja de cálculo o un diccionario de Series

In [ ]:
data = {'Columna 1': [1, 2, 3], 'Columna 2': ['a', 'b', 'c']}
df = pd.DataFrame(data)
print(df)

   Columna 1 Columna 2
0          1         a
1          2         b
2          3         c

# Origenes

Pandas soporta la lectura de una variedad de formatos de archivo, lo que facilita comenzar tu análisis

In [7]:
data = pd.read_csv('https://raw.githubusercontent.com/alvarodemaqua/ISDI-Pandas/main/csv/most-popular.csv', on_bad_lines='skip')

In [8]:
data

,category,rank,show_title,season_title,hours_viewed_first_91_days,runtime,views_first_91_days
0,Films (English),1,Red Notice,NaN,454200000,1.9667,230900000
1,Films (English),2,Don't Look Up,NaN,408600000,2.3833,171400000
2,Films (English),3,The Adam Project,NaN,281000000,1.7833,157600000
3,Films (English),4,Bird Box,NaN,325300000,2.0667,157400000
4,Films (English),5,The Gray Man,NaN,299500000,2.1500,139300000
5,Films (English),6,We Can Be Heroes,NaN,231200000,1.6833,137300000
6,Films (English),7,The Mother,NaN,265900000,1.9500,136400000
7,Films (English),8,Glass Onion: A Knives Out Mystery,NaN,320300000,2.3500,136300000
8,Films (English),9,Extraction,NaN,266900000,1.9667,135700000
9,Films (English),10,Extraction 2,NaN,278700000,2.0667,134900000
10,Films (Non-English),1,Troll,NaN,178600000,1.7333,103000000
11,Films (Non-English),2,Nowhere,NaN,152000000,1.8167,83700000
12,Films (Non-English),3,The Platform,NaN,129700000,1.5667,82800000
13,Films (Non-English),4,Through My Window,NaN,116000000,1.9000,61100000
14,Films (Non-English),5,AKA,NaN,125900000,2.0667,60900000
15,Films (Non-English),6,Blood Red Sky,NaN,124800000,2.0500,60900000
16,Films (Non-English),7,My Name Is Vendetta,NaN,86500000,1.5333,56400000
17,Films (Non-English),8,Black Crab,NaN,103300000,1.9167,53900000
18,Films (Non-English),9,All Quiet on the Western Front,NaN,129400000,2.4833,52100000
19,Films (Non-English),10,Below Zero,NaN,86700000,1.7833,48600000
20,TV (English),1,Wednesday,Wednesday: Season 1,1718800000,6.8167,252100000
21,TV (English),2,Stranger Things,Stranger Things 4,1838000000,13.0667,140700000
22,TV (English),3,DAHMER,DAHMER: Monster: The Jeffrey Dahmer Story,1031100000,8.9167,115600000
23,TV (English),4,Bridgerton,Bridgerton: Season 1,929300000,8.2000,113300000
24,TV (English),5,The Queen's Gambit,The Queen's Gambit: Limited Series,746400000,6.6167,112800000
25,TV (English),6,The Night Agent,The Night Agent: Season 1,803200000,8.1833,98200000
26,TV (English),7,Stranger Things,Stranger Things 3,716100000,7.5500,94800000
27,TV (English),8,Bridgerton,Bridgerton: Season 2,797200000,8.5000,93800000
28,TV (English),9,The Witcher,The Witcher: Season 1,663600000,8.0000,83000000
29,TV (English),10,Queen Charlotte: A Bridgerton Story,NaN,526800000,6.4833,81300000
30,TV (Non-English),1,Squid Game,Squid Game: Season 1,2205200000,8.3167,265200000
31,TV (Non-English),2,Money Heist,Money Heist: Part 4,710200000,6.7000,106000000
32,TV (Non-English),3,Lupin,Lupin: Part 1,396300000,3.9833,99500000
33,TV (Non-English),4,Money Heist,Money Heist: Part 5,900700000,9.0833,99200000
34,TV (Non-English),5,Money Heist,Money Heist: Part 3,519800000,6.5000,80000000
35,TV (Non-English),6,Lupin,Lupin: Part 2,258900000,3.7833,68400000
36,TV (Non-English),7,Who Killed Sara?,Who Killed Sara?: Season 1,392400000,6.7167,58400000
37,TV (Non-English),8,All of Us Are Dead,All of Us Are Dead: Season 1,679300000,12.2333,55500000
38,TV (Non-English),9,Dear Child,Dear Child: Limited Series,245400000,4.8167,50900000
39,TV (Non-English),10,Elite,Elite: Season 3,334800000,6.7000,50000000

In [9]:
excel_data = pd.read_excel('https://github.com/alvarodemaqua/ISDI-Pandas/raw/main/excel/SuperStoreUS-2015.xlsx')

In [10]:
excel_data

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,...,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
0,20847,High,0.01,2.84,0.93,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,2015-01-07,2015-01-08,4.5600,4,13.01,88522
1,20228,Not Specified,0.02,500.98,26.00,5,Ronnie Proctor,Delivery Truck,Home Office,Furniture,...,West,California,San Gabriel,91776,2015-06-13,2015-06-15,4390.3665,12,6362.85,90193
2,21776,Critical,0.06,9.48,7.29,11,Marcus Dunlap,Regular Air,Home Office,Furniture,...,East,New Jersey,Roselle,7203,2015-02-15,2015-02-17,-53.8096,22,211.15,90192
3,24844,Medium,0.09,78.69,19.99,14,Gwendolyn F Tyson,Regular Air,Small Business,Furniture,...,Central,Minnesota,Prior Lake,55372,2015-05-12,2015-05-14,803.4705,16,1164.45,86838
4,24846,Medium,0.08,3.28,2.31,14,Gwendolyn F Tyson,Regular Air,Small Business,Office Supplies,...,Central,Minnesota,Prior Lake,55372,2015-05-12,2015-05-13,-24.0300,7,22.23,86838
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1947,19842,High,0.01,10.90,7.46,3397,Andrea Shaw,Regular Air,Small Business,Office Supplies,...,Central,Illinois,Danville,61832,2015-03-11,2015-03-12,-116.7600,18,207.31,87536
1948,19843,High,0.10,7.99,5.03,3397,Andrea Shaw,Regular Air,Small Business,Technology,...,Central,Illinois,Danville,61832,2015-03-11,2015-03-12,-160.9520,22,143.12,87536
1949,26208,Not Specified,0.08,11.97,5.81,3399,Marvin Reid,Regular Air,Small Business,Office Supplies,...,Central,Illinois,Des Plaines,60016,2015-03-29,2015-03-31,-41.8700,5,59.98,87534
1950,24911,Medium,0.10,9.38,4.93,3400,Florence Gold,Express Air,Small Business,Furniture,...,East,West Virginia,Fairmont,26554,2015-04-04,2015-04-04,-24.7104,15,135.78,87537
1951,25914,High,0.10,105.98,13.99,3403,Tammy Buckley,Express Air,Consumer,Furniture,...,West,Wyoming,Cheyenne,82001,2015-02-08,2015-02-11,349.4850,5,506.50,87530

In [11]:
data.head()

,category,rank,show_title,season_title,hours_viewed_first_91_days,runtime,views_first_91_days
0,Films (English),1,Red Notice,NaN,454200000,1.9667,230900000
1,Films (English),2,Don't Look Up,NaN,408600000,2.3833,171400000
2,Films (English),3,The Adam Project,NaN,281000000,1.7833,157600000
3,Films (English),4,Bird Box,NaN,325300000,2.0667,157400000
4,Films (English),5,The Gray Man,NaN,299500000,2.1500,139300000

In [12]:
data.tail()

,category,rank,show_title,season_title,hours_viewed_first_91_days,runtime,views_first_91_days
35,TV (Non-English),6,Lupin,Lupin: Part 2,258900000,3.7833,68400000
36,TV (Non-English),7,Who Killed Sara?,Who Killed Sara?: Season 1,392400000,6.7167,58400000
37,TV (Non-English),8,All of Us Are Dead,All of Us Are Dead: Season 1,679300000,12.2333,55500000
38,TV (Non-English),9,Dear Child,Dear Child: Limited Series,245400000,4.8167,50900000
39,TV (Non-English),10,Elite,Elite: Season 3,334800000,6.7000,50000000

In [13]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 7 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   category                    40 non-null     object
 1   rank                        40 non-null     int64
 2   show_title                  40 non-null     object
 3   season_title                19 non-null     object
 4   hours_viewed_first_91_days  40 non-null     int64
 5   runtime                     40 non-null     float64
 6   views_first_91_days         40 non-null     int64
dtypes: float64(1), int64(3), object(3)
memory usage: 2.3+ KB

In [14]:
data.describe()

            rank  hours_viewed_first_91_days    runtime  views_first_91_days
count  40.000000                4.000000e+01  40.000000         4.000000e+01
mean    5.500000                5.194500e+08   4.759585         1.079825e+08
std     2.908872                4.851032e+08   3.257445         5.356564e+07
min     1.000000                8.650000e+07   1.533300         4.860000e+07
25%     3.000000                2.180500e+08   1.962525         6.105000e+07
50%     5.500000                3.300500e+08   3.133300         9.870000e+07
75%     8.000000                7.116750e+08   7.000025         1.363250e+08
max    10.000000                2.205200e+09  13.066700         2.652000e+08

In [15]:
data.isnull().sum()

category                       0
rank                           0
show_title                     0
season_title                  21
hours_viewed_first_91_days     0
runtime                        0
views_first_91_days            0
dtype: int64

In [16]:
data.dropna()

,category,rank,show_title,season_title,hours_viewed_first_91_days,runtime,views_first_91_days
20,TV (English),1,Wednesday,Wednesday: Season 1,1718800000,6.8167,252100000
21,TV (English),2,Stranger Things,Stranger Things 4,1838000000,13.0667,140700000
22,TV (English),3,DAHMER,DAHMER: Monster: The Jeffrey Dahmer Story,1031100000,8.9167,115600000
23,TV (English),4,Bridgerton,Bridgerton: Season 1,929300000,8.2000,113300000
24,TV (English),5,The Queen's Gambit,The Queen's Gambit: Limited Series,746400000,6.6167,112800000
25,TV (English),6,The Night Agent,The Night Agent: Season 1,803200000,8.1833,98200000
26,TV (English),7,Stranger Things,Stranger Things 3,716100000,7.5500,94800000
27,TV (English),8,Bridgerton,Bridgerton: Season 2,797200000,8.5000,93800000
28,TV (English),9,The Witcher,The Witcher: Season 1,663600000,8.0000,83000000
30,TV (Non-English),1,Squid Game,Squid Game: Season 1,2205200000,8.3167,265200000
31,TV (Non-English),2,Money Heist,Money Heist: Part 4,710200000,6.7000,106000000
32,TV (Non-English),3,Lupin,Lupin: Part 1,396300000,3.9833,99500000
33,TV (Non-English),4,Money Heist,Money Heist: Part 5,900700000,9.0833,99200000
34,TV (Non-English),5,Money Heist,Money Heist: Part 3,519800000,6.5000,80000000
35,TV (Non-English),6,Lupin,Lupin: Part 2,258900000,3.7833,68400000
36,TV (Non-English),7,Who Killed Sara?,Who Killed Sara?: Season 1,392400000,6.7167,58400000
37,TV (Non-English),8,All of Us Are Dead,All of Us Are Dead: Season 1,679300000,12.2333,55500000
38,TV (Non-English),9,Dear Child,Dear Child: Limited Series,245400000,4.8167,50900000
39,TV (Non-English),10,Elite,Elite: Season 3,334800000,6.7000,50000000

In [17]:
data.dropna(how='all')

,category,rank,show_title,season_title,hours_viewed_first_91_days,runtime,views_first_91_days
0,Films (English),1,Red Notice,NaN,454200000,1.9667,230900000
1,Films (English),2,Don't Look Up,NaN,408600000,2.3833,171400000
2,Films (English),3,The Adam Project,NaN,281000000,1.7833,157600000
3,Films (English),4,Bird Box,NaN,325300000,2.0667,157400000
4,Films (English),5,The Gray Man,NaN,299500000,2.1500,139300000
5,Films (English),6,We Can Be Heroes,NaN,231200000,1.6833,137300000
6,Films (English),7,The Mother,NaN,265900000,1.9500,136400000
7,Films (English),8,Glass Onion: A Knives Out Mystery,NaN,320300000,2.3500,136300000
8,Films (English),9,Extraction,NaN,266900000,1.9667,135700000
9,Films (English),10,Extraction 2,NaN,278700000,2.0667,134900000
10,Films (Non-English),1,Troll,NaN,178600000,1.7333,103000000
11,Films (Non-English),2,Nowhere,NaN,152000000,1.8167,83700000
12,Films (Non-English),3,The Platform,NaN,129700000,1.5667,82800000
13,Films (Non-English),4,Through My Window,NaN,116000000,1.9000,61100000
14,Films (Non-English),5,AKA,NaN,125900000,2.0667,60900000
15,Films (Non-English),6,Blood Red Sky,NaN,124800000,2.0500,60900000
16,Films (Non-English),7,My Name Is Vendetta,NaN,86500000,1.5333,56400000
17,Films (Non-English),8,Black Crab,NaN,103300000,1.9167,53900000
18,Films (Non-English),9,All Quiet on the Western Front,NaN,129400000,2.4833,52100000
19,Films (Non-English),10,Below Zero,NaN,86700000,1.7833,48600000
20,TV (English),1,Wednesday,Wednesday: Season 1,1718800000,6.8167,252100000
21,TV (English),2,Stranger Things,Stranger Things 4,1838000000,13.0667,140700000
22,TV (English),3,DAHMER,DAHMER: Monster: The Jeffrey Dahmer Story,1031100000,8.9167,115600000
23,TV (English),4,Bridgerton,Bridgerton: Season 1,929300000,8.2000,113300000
24,TV (English),5,The Queen's Gambit,The Queen's Gambit: Limited Series,746400000,6.6167,112800000
25,TV (English),6,The Night Agent,The Night Agent: Season 1,803200000,8.1833,98200000
26,TV (English),7,Stranger Things,Stranger Things 3,716100000,7.5500,94800000
27,TV (English),8,Bridgerton,Bridgerton: Season 2,797200000,8.5000,93800000
28,TV (English),9,The Witcher,The Witcher: Season 1,663600000,8.0000,83000000
29,TV (English),10,Queen Charlotte: A Bridgerton Story,NaN,526800000,6.4833,81300000
30,TV (Non-English),1,Squid Game,Squid Game: Season 1,2205200000,8.3167,265200000
31,TV (Non-English),2,Money Heist,Money Heist: Part 4,710200000,6.7000,106000000
32,TV (Non-English),3,Lupin,Lupin: Part 1,396300000,3.9833,99500000
33,TV (Non-English),4,Money Heist,Money Heist: Part 5,900700000,9.0833,99200000
34,TV (Non-English),5,Money Heist,Money Heist: Part 3,519800000,6.5000,80000000
35,TV (Non-English),6,Lupin,Lupin: Part 2,258900000,3.7833,68400000
36,TV (Non-English),7,Who Killed Sara?,Who Killed Sara?: Season 1,392400000,6.7167,58400000
37,TV (Non-English),8,All of Us Are Dead,All of Us Are Dead: Season 1,679300000,12.2333,55500000
38,TV (Non-English),9,Dear Child,Dear Child: Limited Series,245400000,4.8167,50900000
39,TV (Non-English),10,Elite,Elite: Season 3,334800000,6.7000,50000000

In [18]:
value = {'season_title': 'No aplica'}
data.fillna(value = value)

,category,rank,show_title,season_title,hours_viewed_first_91_days,runtime,views_first_91_days
0,Films (English),1,Red Notice,No aplica,454200000,1.9667,230900000
1,Films (English),2,Don't Look Up,No aplica,408600000,2.3833,171400000
2,Films (English),3,The Adam Project,No aplica,281000000,1.7833,157600000
3,Films (English),4,Bird Box,No aplica,325300000,2.0667,157400000
4,Films (English),5,The Gray Man,No aplica,299500000,2.1500,139300000
5,Films (English),6,We Can Be Heroes,No aplica,231200000,1.6833,137300000
6,Films (English),7,The Mother,No aplica,265900000,1.9500,136400000
7,Films (English),8,Glass Onion: A Knives Out Mystery,No aplica,320300000,2.3500,136300000
8,Films (English),9,Extraction,No aplica,266900000,1.9667,135700000
9,Films (English),10,Extraction 2,No aplica,278700000,2.0667,134900000
10,Films (Non-English),1,Troll,No aplica,178600000,1.7333,103000000
11,Films (Non-English),2,Nowhere,No aplica,152000000,1.8167,83700000
12,Films (Non-English),3,The Platform,No aplica,129700000,1.5667,82800000
13,Films (Non-English),4,Through My Window,No aplica,116000000,1.9000,61100000
14,Films (Non-English),5,AKA,No aplica,125900000,2.0667,60900000
15,Films (Non-English),6,Blood Red Sky,No aplica,124800000,2.0500,60900000
16,Films (Non-English),7,My Name Is Vendetta,No aplica,86500000,1.5333,56400000
17,Films (Non-English),8,Black Crab,No aplica,103300000,1.9167,53900000
18,Films (Non-English),9,All Quiet on the Western Front,No aplica,129400000,2.4833,52100000
19,Films (Non-English),10,Below Zero,No aplica,86700000,1.7833,48600000
20,TV (English),1,Wednesday,Wednesday: Season 1,1718800000,6.8167,252100000
21,TV (English),2,Stranger Things,Stranger Things 4,1838000000,13.0667,140700000
22,TV (English),3,DAHMER,DAHMER: Monster: The Jeffrey Dahmer Story,1031100000,8.9167,115600000
23,TV (English),4,Bridgerton,Bridgerton: Season 1,929300000,8.2000,113300000
24,TV (English),5,The Queen's Gambit,The Queen's Gambit: Limited Series,746400000,6.6167,112800000
25,TV (English),6,The Night Agent,The Night Agent: Season 1,803200000,8.1833,98200000
26,TV (English),7,Stranger Things,Stranger Things 3,716100000,7.5500,94800000
27,TV (English),8,Bridgerton,Bridgerton: Season 2,797200000,8.5000,93800000
28,TV (English),9,The Witcher,The Witcher: Season 1,663600000,8.0000,83000000
29,TV (English),10,Queen Charlotte: A Bridgerton Story,No aplica,526800000,6.4833,81300000
30,TV (Non-English),1,Squid Game,Squid Game: Season 1,2205200000,8.3167,265200000
31,TV (Non-English),2,Money Heist,Money Heist: Part 4,710200000,6.7000,106000000
32,TV (Non-English),3,Lupin,Lupin: Part 1,396300000,3.9833,99500000
33,TV (Non-English),4,Money Heist,Money Heist: Part 5,900700000,9.0833,99200000
34,TV (Non-English),5,Money Heist,Money Heist: Part 3,519800000,6.5000,80000000
35,TV (Non-English),6,Lupin,Lupin: Part 2,258900000,3.7833,68400000
36,TV (Non-English),7,Who Killed Sara?,Who Killed Sara?: Season 1,392400000,6.7167,58400000
37,TV (Non-English),8,All of Us Are Dead,All of Us Are Dead: Season 1,679300000,12.2333,55500000
38,TV (Non-English),9,Dear Child,Dear Child: Limited Series,245400000,4.8167,50900000
39,TV (Non-English),10,Elite,Elite: Season 3,334800000,6.7000,50000000

# Selección, filtrado y alteración

In [20]:
columna = data.show_title

In [21]:
columna

0                              Red Notice
1                           Don't Look Up
2                        The Adam Project
3                                Bird Box
4                            The Gray Man
5                        We Can Be Heroes
6                              The Mother
7       Glass Onion: A Knives Out Mystery
8                              Extraction
9                            Extraction 2
10                                  Troll
11                                Nowhere
12                           The Platform
13                      Through My Window
14                                    AKA
15                          Blood Red Sky
16                    My Name Is Vendetta
17                             Black Crab
18         All Quiet on the Western Front
19                             Below Zero
20                              Wednesday
21                        Stranger Things
22                                 DAHMER
23                             Bridgerton
24                     The Queen's Gambit
25                        The Night Agent
26                        Stranger Things
27                             Bridgerton
28                            The Witcher
29    Queen Charlotte: A Bridgerton Story
30                             Squid Game
31                            Money Heist
32                                  Lupin
33                            Money Heist
34                            Money Heist
35                                  Lupin
36                       Who Killed Sara?
37                     All of Us Are Dead
38                             Dear Child
39                                  Elite
Name: show_title, dtype: object

In [25]:
columnas = data[['show_title', 'views_first_91_days']]

In [26]:
columnas

                             show_title  views_first_91_days
0                            Red Notice            230900000
1                         Don't Look Up            171400000
2                      The Adam Project            157600000
3                              Bird Box            157400000
4                          The Gray Man            139300000
5                      We Can Be Heroes            137300000
6                            The Mother            136400000
7     Glass Onion: A Knives Out Mystery            136300000
8                            Extraction            135700000
9                          Extraction 2            134900000
10                                Troll            103000000
11                              Nowhere             83700000
12                         The Platform             82800000
13                    Through My Window             61100000
14                                  AKA             60900000
15                        Blood Red Sky             60900000
16                  My Name Is Vendetta             56400000
17                           Black Crab             53900000
18       All Quiet on the Western Front             52100000
19                           Below Zero             48600000
20                            Wednesday            252100000
21                      Stranger Things            140700000
22                               DAHMER            115600000
23                           Bridgerton            113300000
24                   The Queen's Gambit            112800000
25                      The Night Agent             98200000
26                      Stranger Things             94800000
27                           Bridgerton             93800000
28                          The Witcher             83000000
29  Queen Charlotte: A Bridgerton Story             81300000
30                           Squid Game            265200000
31                          Money Heist            106000000
32                                Lupin             99500000
33                          Money Heist             99200000
34                          Money Heist             80000000
35                                Lupin             68400000
36                     Who Killed Sara?             58400000
37                   All of Us Are Dead             55500000
38                           Dear Child             50900000
39                                Elite             50000000

In [27]:
data.iloc[3] # Selecciona fila 4

category                      Films (English)
rank                                        4
show_title                           Bird Box
season_title                              NaN
hours_viewed_first_91_days          325300000
runtime                                2.0667
views_first_91_days                 157400000
Name: 3, dtype: object

In [28]:
rango_filas = data.iloc[1:5]

In [29]:
rango_filas

,category,rank,show_title,season_title,hours_viewed_first_91_days,runtime,views_first_91_days
1,Films (English),2,Don't Look Up,NaN,408600000,2.3833,171400000
2,Films (English),3,The Adam Project,NaN,281000000,1.7833,157600000
3,Films (English),4,Bird Box,NaN,325300000,2.0667,157400000
4,Films (English),5,The Gray Man,NaN,299500000,2.1500,139300000

In [33]:
filtrado = data[data['category'] == 'Films (English)']

In [34]:
filtrado

,category,rank,show_title,season_title,hours_viewed_first_91_days,runtime,views_first_91_days
0,Films (English),1,Red Notice,NaN,454200000,1.9667,230900000
1,Films (English),2,Don't Look Up,NaN,408600000,2.3833,171400000
2,Films (English),3,The Adam Project,NaN,281000000,1.7833,157600000
3,Films (English),4,Bird Box,NaN,325300000,2.0667,157400000
4,Films (English),5,The Gray Man,NaN,299500000,2.1500,139300000
5,Films (English),6,We Can Be Heroes,NaN,231200000,1.6833,137300000
6,Films (English),7,The Mother,NaN,265900000,1.9500,136400000
7,Films (English),8,Glass Onion: A Knives Out Mystery,NaN,320300000,2.3500,136300000
8,Films (English),9,Extraction,NaN,266900000,1.9667,135700000
9,Films (English),10,Extraction 2,NaN,278700000,2.0667,134900000

In [35]:
nuevo_filtrado = data[(data['category'] == 'Films (English)') & (data['hours_viewed_first_91_days'] > 300000000)]

In [36]:
nuevo_filtrado

,category,rank,show_title,season_title,hours_viewed_first_91_days,runtime,views_first_91_days
0,Films (English),1,Red Notice,NaN,454200000,1.9667,230900000
1,Films (English),2,Don't Look Up,NaN,408600000,2.3833,171400000
3,Films (English),4,Bird Box,NaN,325300000,2.0667,157400000
7,Films (English),8,Glass Onion: A Knives Out Mystery,NaN,320300000,2.3500,136300000

In [37]:
copia_data = data

In [38]:
copia_data['horas_por_vista'] = copia_data['hours_viewed_first_91_days'] / copia_data['views_first_91_days']

In [39]:
copia_data

,category,rank,show_title,season_title,hours_viewed_first_91_days,runtime,views_first_91_days,horas_por_vista
0,Films (English),1,Red Notice,NaN,454200000,1.9667,230900000,1.967085
1,Films (English),2,Don't Look Up,NaN,408600000,2.3833,171400000,2.383897
2,Films (English),3,The Adam Project,NaN,281000000,1.7833,157600000,1.782995
3,Films (English),4,Bird Box,NaN,325300000,2.0667,157400000,2.066709
4,Films (English),5,The Gray Man,NaN,299500000,2.1500,139300000,2.150036
5,Films (English),6,We Can Be Heroes,NaN,231200000,1.6833,137300000,1.683904
6,Films (English),7,The Mother,NaN,265900000,1.9500,136400000,1.949413
7,Films (English),8,Glass Onion: A Knives Out Mystery,NaN,320300000,2.3500,136300000,2.349963
8,Films (English),9,Extraction,NaN,266900000,1.9667,135700000,1.966839
9,Films (English),10,Extraction 2,NaN,278700000,2.0667,134900000,2.065975
10,Films (Non-English),1,Troll,NaN,178600000,1.7333,103000000,1.733981
11,Films (Non-English),2,Nowhere,NaN,152000000,1.8167,83700000,1.816010
12,Films (Non-English),3,The Platform,NaN,129700000,1.5667,82800000,1.566425
13,Films (Non-English),4,Through My Window,NaN,116000000,1.9000,61100000,1.898527
14,Films (Non-English),5,AKA,NaN,125900000,2.0667,60900000,2.067323
15,Films (Non-English),6,Blood Red Sky,NaN,124800000,2.0500,60900000,2.049261
16,Films (Non-English),7,My Name Is Vendetta,NaN,86500000,1.5333,56400000,1.533688
17,Films (Non-English),8,Black Crab,NaN,103300000,1.9167,53900000,1.916512
18,Films (Non-English),9,All Quiet on the Western Front,NaN,129400000,2.4833,52100000,2.483685
19,Films (Non-English),10,Below Zero,NaN,86700000,1.7833,48600000,1.783951
20,TV (English),1,Wednesday,Wednesday: Season 1,1718800000,6.8167,252100000,6.817929
21,TV (English),2,Stranger Things,Stranger Things 4,1838000000,13.0667,140700000,13.063255
22,TV (English),3,DAHMER,DAHMER: Monster: The Jeffrey Dahmer Story,1031100000,8.9167,115600000,8.919550
23,TV (English),4,Bridgerton,Bridgerton: Season 1,929300000,8.2000,113300000,8.202118
24,TV (English),5,The Queen's Gambit,The Queen's Gambit: Limited Series,746400000,6.6167,112800000,6.617021
25,TV (English),6,The Night Agent,The Night Agent: Season 1,803200000,8.1833,98200000,8.179226
26,TV (English),7,Stranger Things,Stranger Things 3,716100000,7.5500,94800000,7.553797
27,TV (English),8,Bridgerton,Bridgerton: Season 2,797200000,8.5000,93800000,8.498934
28,TV (English),9,The Witcher,The Witcher: Season 1,663600000,8.0000,83000000,7.995181
29,TV (English),10,Queen Charlotte: A Bridgerton Story,NaN,526800000,6.4833,81300000,6.479705
30,TV (Non-English),1,Squid Game,Squid Game: Season 1,2205200000,8.3167,265200000,8.315234
31,TV (Non-English),2,Money Heist,Money Heist: Part 4,710200000,6.7000,106000000,6.700000
32,TV (Non-English),3,Lupin,Lupin: Part 1,396300000,3.9833,99500000,3.982915
33,TV (Non-English),4,Money Heist,Money Heist: Part 5,900700000,9.0833,99200000,9.079637
34,TV (Non-English),5,Money Heist,Money Heist: Part 3,519800000,6.5000,80000000,6.497500
35,TV (Non-English),6,Lupin,Lupin: Part 2,258900000,3.7833,68400000,3.785088
36,TV (Non-English),7,Who Killed Sara?,Who Killed Sara?: Season 1,392400000,6.7167,58400000,6.719178
37,TV (Non-English),8,All of Us Are Dead,All of Us Are Dead: Season 1,679300000,12.2333,55500000,12.239640
38,TV (Non-English),9,Dear Child,Dear Child: Limited Series,245400000,4.8167,50900000,4.821218
39,TV (Non-English),10,Elite,Elite: Season 3,334800000,6.7000,50000000,6.696000

In [41]:
copia_data['conversion_horas_a_dias'] = copia_data['hours_viewed_first_91_days'] / 24

In [42]:
copia_data

,category,rank,show_title,season_title,hours_viewed_first_91_days,runtime,views_first_91_days,horas_por_vista,conversion_horas_a_dias
0,Films (English),1,Red Notice,NaN,454200000,1.9667,230900000,1.967085,1.892500e+07
1,Films (English),2,Don't Look Up,NaN,408600000,2.3833,171400000,2.383897,1.702500e+07
2,Films (English),3,The Adam Project,NaN,281000000,1.7833,157600000,1.782995,1.170833e+07
3,Films (English),4,Bird Box,NaN,325300000,2.0667,157400000,2.066709,1.355417e+07
4,Films (English),5,The Gray Man,NaN,299500000,2.1500,139300000,2.150036,1.247917e+07
5,Films (English),6,We Can Be Heroes,NaN,231200000,1.6833,137300000,1.683904,9.633333e+06
6,Films (English),7,The Mother,NaN,265900000,1.9500,136400000,1.949413,1.107917e+07
7,Films (English),8,Glass Onion: A Knives Out Mystery,NaN,320300000,2.3500,136300000,2.349963,1.334583e+07
8,Films (English),9,Extraction,NaN,266900000,1.9667,135700000,1.966839,1.112083e+07
9,Films (English),10,Extraction 2,NaN,278700000,2.0667,134900000,2.065975,1.161250e+07
10,Films (Non-English),1,Troll,NaN,178600000,1.7333,103000000,1.733981,7.441667e+06
11,Films (Non-English),2,Nowhere,NaN,152000000,1.8167,83700000,1.816010,6.333333e+06
12,Films (Non-English),3,The Platform,NaN,129700000,1.5667,82800000,1.566425,5.404167e+06
13,Films (Non-English),4,Through My Window,NaN,116000000,1.9000,61100000,1.898527,4.833333e+06
14,Films (Non-English),5,AKA,NaN,125900000,2.0667,60900000,2.067323,5.245833e+06
15,Films (Non-English),6,Blood Red Sky,NaN,124800000,2.0500,60900000,2.049261,5.200000e+06
16,Films (Non-English),7,My Name Is Vendetta,NaN,86500000,1.5333,56400000,1.533688,3.604167e+06
17,Films (Non-English),8,Black Crab,NaN,103300000,1.9167,53900000,1.916512,4.304167e+06
18,Films (Non-English),9,All Quiet on the Western Front,NaN,129400000,2.4833,52100000,2.483685,5.391667e+06
19,Films (Non-English),10,Below Zero,NaN,86700000,1.7833,48600000,1.783951,3.612500e+06
20,TV (English),1,Wednesday,Wednesday: Season 1,1718800000,6.8167,252100000,6.817929,7.161667e+07
21,TV (English),2,Stranger Things,Stranger Things 4,1838000000,13.0667,140700000,13.063255,7.658333e+07
22,TV (English),3,DAHMER,DAHMER: Monster: The Jeffrey Dahmer Story,1031100000,8.9167,115600000,8.919550,4.296250e+07
23,TV (English),4,Bridgerton,Bridgerton: Season 1,929300000,8.2000,113300000,8.202118,3.872083e+07
24,TV (English),5,The Queen's Gambit,The Queen's Gambit: Limited Series,746400000,6.6167,112800000,6.617021,3.110000e+07
25,TV (English),6,The Night Agent,The Night Agent: Season 1,803200000,8.1833,98200000,8.179226,3.346667e+07
26,TV (English),7,Stranger Things,Stranger Things 3,716100000,7.5500,94800000,7.553797,2.983750e+07
27,TV (English),8,Bridgerton,Bridgerton: Season 2,797200000,8.5000,93800000,8.498934,3.321667e+07
28,TV (English),9,The Witcher,The Witcher: Season 1,663600000,8.0000,83000000,7.995181,2.765000e+07
29,TV (English),10,Queen Charlotte: A Bridgerton Story,NaN,526800000,6.4833,81300000,6.479705,2.195000e+07
30,TV (Non-English),1,Squid Game,Squid Game: Season 1,2205200000,8.3167,265200000,8.315234,9.188333e+07
31,TV (Non-English),2,Money Heist,Money Heist: Part 4,710200000,6.7000,106000000,6.700000,2.959167e+07
32,TV (Non-English),3,Lupin,Lupin: Part 1,396300000,3.9833,99500000,3.982915,1.651250e+07
33,TV (Non-English),4,Money Heist,Money Heist: Part 5,900700000,9.0833,99200000,9.079637,3.752917e+07
34,TV (Non-English),5,Money Heist,Money Heist: Part 3,519800000,6.5000,80000000,6.497500,2.165833e+07
35,TV (Non-English),6,Lupin,Lupin: Part 2,258900000,3.7833,68400000,3.785088,1.078750e+07
36,TV (Non-English),7,Who Killed Sara?,Who Killed Sara?: Season 1,392400000,6.7167,58400000,6.719178,1.635000e+07
37,TV (Non-English),8,All of Us Are Dead,All of Us Are Dead: Season 1,679300000,12.2333,55500000,12.239640,2.830417e+07
38,TV (Non-English),9,Dear Child,Dear Child: Limited Series,245400000,4.8167,50900000,4.821218,1.022500e+07
39,TV (Non-English),10,Elite,Elite: Season 3,334800000,6.7000,50000000,6.696000,1.395000e+07

In [44]:
copia_data.drop('horas_por_vista', axis=1)

,category,rank,show_title,season_title,hours_viewed_first_91_days,runtime,views_first_91_days,conversion_horas_a_dias
0,Films (English),1,Red Notice,NaN,454200000,1.9667,230900000,1.892500e+07
1,Films (English),2,Don't Look Up,NaN,408600000,2.3833,171400000,1.702500e+07
2,Films (English),3,The Adam Project,NaN,281000000,1.7833,157600000,1.170833e+07
3,Films (English),4,Bird Box,NaN,325300000,2.0667,157400000,1.355417e+07
4,Films (English),5,The Gray Man,NaN,299500000,2.1500,139300000,1.247917e+07
5,Films (English),6,We Can Be Heroes,NaN,231200000,1.6833,137300000,9.633333e+06
6,Films (English),7,The Mother,NaN,265900000,1.9500,136400000,1.107917e+07
7,Films (English),8,Glass Onion: A Knives Out Mystery,NaN,320300000,2.3500,136300000,1.334583e+07
8,Films (English),9,Extraction,NaN,266900000,1.9667,135700000,1.112083e+07
9,Films (English),10,Extraction 2,NaN,278700000,2.0667,134900000,1.161250e+07
10,Films (Non-English),1,Troll,NaN,178600000,1.7333,103000000,7.441667e+06
11,Films (Non-English),2,Nowhere,NaN,152000000,1.8167,83700000,6.333333e+06
12,Films (Non-English),3,The Platform,NaN,129700000,1.5667,82800000,5.404167e+06
13,Films (Non-English),4,Through My Window,NaN,116000000,1.9000,61100000,4.833333e+06
14,Films (Non-English),5,AKA,NaN,125900000,2.0667,60900000,5.245833e+06
15,Films (Non-English),6,Blood Red Sky,NaN,124800000,2.0500,60900000,5.200000e+06
16,Films (Non-English),7,My Name Is Vendetta,NaN,86500000,1.5333,56400000,3.604167e+06
17,Films (Non-English),8,Black Crab,NaN,103300000,1.9167,53900000,4.304167e+06
18,Films (Non-English),9,All Quiet on the Western Front,NaN,129400000,2.4833,52100000,5.391667e+06
19,Films (Non-English),10,Below Zero,NaN,86700000,1.7833,48600000,3.612500e+06
20,TV (English),1,Wednesday,Wednesday: Season 1,1718800000,6.8167,252100000,7.161667e+07
21,TV (English),2,Stranger Things,Stranger Things 4,1838000000,13.0667,140700000,7.658333e+07
22,TV (English),3,DAHMER,DAHMER: Monster: The Jeffrey Dahmer Story,1031100000,8.9167,115600000,4.296250e+07
23,TV (English),4,Bridgerton,Bridgerton: Season 1,929300000,8.2000,113300000,3.872083e+07
24,TV (English),5,The Queen's Gambit,The Queen's Gambit: Limited Series,746400000,6.6167,112800000,3.110000e+07
25,TV (English),6,The Night Agent,The Night Agent: Season 1,803200000,8.1833,98200000,3.346667e+07
26,TV (English),7,Stranger Things,Stranger Things 3,716100000,7.5500,94800000,2.983750e+07
27,TV (English),8,Bridgerton,Bridgerton: Season 2,797200000,8.5000,93800000,3.321667e+07
28,TV (English),9,The Witcher,The Witcher: Season 1,663600000,8.0000,83000000,2.765000e+07
29,TV (English),10,Queen Charlotte: A Bridgerton Story,NaN,526800000,6.4833,81300000,2.195000e+07
30,TV (Non-English),1,Squid Game,Squid Game: Season 1,2205200000,8.3167,265200000,9.188333e+07
31,TV (Non-English),2,Money Heist,Money Heist: Part 4,710200000,6.7000,106000000,2.959167e+07
32,TV (Non-English),3,Lupin,Lupin: Part 1,396300000,3.9833,99500000,1.651250e+07
33,TV (Non-English),4,Money Heist,Money Heist: Part 5,900700000,9.0833,99200000,3.752917e+07
34,TV (Non-English),5,Money Heist,Money Heist: Part 3,519800000,6.5000,80000000,2.165833e+07
35,TV (Non-English),6,Lupin,Lupin: Part 2,258900000,3.7833,68400000,1.078750e+07
36,TV (Non-English),7,Who Killed Sara?,Who Killed Sara?: Season 1,392400000,6.7167,58400000,1.635000e+07
37,TV (Non-English),8,All of Us Are Dead,All of Us Are Dead: Season 1,679300000,12.2333,55500000,2.830417e+07
38,TV (Non-English),9,Dear Child,Dear Child: Limited Series,245400000,4.8167,50900000,1.022500e+07
39,TV (Non-English),10,Elite,Elite: Season 3,334800000,6.7000,50000000,1.395000e+07

In [45]:
copia_data.drop(copia_data.index[0], inplace=True)

In [46]:
copia_data

,category,rank,show_title,season_title,hours_viewed_first_91_days,runtime,views_first_91_days,horas_por_vista,conversion_horas_a_dias
1,Films (English),2,Don't Look Up,NaN,408600000,2.3833,171400000,2.383897,1.702500e+07
2,Films (English),3,The Adam Project,NaN,281000000,1.7833,157600000,1.782995,1.170833e+07
3,Films (English),4,Bird Box,NaN,325300000,2.0667,157400000,2.066709,1.355417e+07
4,Films (English),5,The Gray Man,NaN,299500000,2.1500,139300000,2.150036,1.247917e+07
5,Films (English),6,We Can Be Heroes,NaN,231200000,1.6833,137300000,1.683904,9.633333e+06
6,Films (English),7,The Mother,NaN,265900000,1.9500,136400000,1.949413,1.107917e+07
7,Films (English),8,Glass Onion: A Knives Out Mystery,NaN,320300000,2.3500,136300000,2.349963,1.334583e+07
8,Films (English),9,Extraction,NaN,266900000,1.9667,135700000,1.966839,1.112083e+07
9,Films (English),10,Extraction 2,NaN,278700000,2.0667,134900000,2.065975,1.161250e+07
10,Films (Non-English),1,Troll,NaN,178600000,1.7333,103000000,1.733981,7.441667e+06
11,Films (Non-English),2,Nowhere,NaN,152000000,1.8167,83700000,1.816010,6.333333e+06
12,Films (Non-English),3,The Platform,NaN,129700000,1.5667,82800000,1.566425,5.404167e+06
13,Films (Non-English),4,Through My Window,NaN,116000000,1.9000,61100000,1.898527,4.833333e+06
14,Films (Non-English),5,AKA,NaN,125900000,2.0667,60900000,2.067323,5.245833e+06
15,Films (Non-English),6,Blood Red Sky,NaN,124800000,2.0500,60900000,2.049261,5.200000e+06
16,Films (Non-English),7,My Name Is Vendetta,NaN,86500000,1.5333,56400000,1.533688,3.604167e+06
17,Films (Non-English),8,Black Crab,NaN,103300000,1.9167,53900000,1.916512,4.304167e+06
18,Films (Non-English),9,All Quiet on the Western Front,NaN,129400000,2.4833,52100000,2.483685,5.391667e+06
19,Films (Non-English),10,Below Zero,NaN,86700000,1.7833,48600000,1.783951,3.612500e+06
20,TV (English),1,Wednesday,Wednesday: Season 1,1718800000,6.8167,252100000,6.817929,7.161667e+07
21,TV (English),2,Stranger Things,Stranger Things 4,1838000000,13.0667,140700000,13.063255,7.658333e+07
22,TV (English),3,DAHMER,DAHMER: Monster: The Jeffrey Dahmer Story,1031100000,8.9167,115600000,8.919550,4.296250e+07
23,TV (English),4,Bridgerton,Bridgerton: Season 1,929300000,8.2000,113300000,8.202118,3.872083e+07
24,TV (English),5,The Queen's Gambit,The Queen's Gambit: Limited Series,746400000,6.6167,112800000,6.617021,3.110000e+07
25,TV (English),6,The Night Agent,The Night Agent: Season 1,803200000,8.1833,98200000,8.179226,3.346667e+07
26,TV (English),7,Stranger Things,Stranger Things 3,716100000,7.5500,94800000,7.553797,2.983750e+07
27,TV (English),8,Bridgerton,Bridgerton: Season 2,797200000,8.5000,93800000,8.498934,3.321667e+07
28,TV (English),9,The Witcher,The Witcher: Season 1,663600000,8.0000,83000000,7.995181,2.765000e+07
29,TV (English),10,Queen Charlotte: A Bridgerton Story,NaN,526800000,6.4833,81300000,6.479705,2.195000e+07
30,TV (Non-English),1,Squid Game,Squid Game: Season 1,2205200000,8.3167,265200000,8.315234,9.188333e+07
31,TV (Non-English),2,Money Heist,Money Heist: Part 4,710200000,6.7000,106000000,6.700000,2.959167e+07
32,TV (Non-English),3,Lupin,Lupin: Part 1,396300000,3.9833,99500000,3.982915,1.651250e+07
33,TV (Non-English),4,Money Heist,Money Heist: Part 5,900700000,9.0833,99200000,9.079637,3.752917e+07
34,TV (Non-English),5,Money Heist,Money Heist: Part 3,519800000,6.5000,80000000,6.497500,2.165833e+07
35,TV (Non-English),6,Lupin,Lupin: Part 2,258900000,3.7833,68400000,3.785088,1.078750e+07
36,TV (Non-English),7,Who Killed Sara?,Who Killed Sara?: Season 1,392400000,6.7167,58400000,6.719178,1.635000e+07
37,TV (Non-English),8,All of Us Are Dead,All of Us Are Dead: Season 1,679300000,12.2333,55500000,12.239640,2.830417e+07
38,TV (Non-English),9,Dear Child,Dear Child: Limited Series,245400000,4.8167,50900000,4.821218,1.022500e+07
39,TV (Non-English),10,Elite,Elite: Season 3,334800000,6.7000,50000000,6.696000,1.395000e+07

In [47]:
agrupacion = copia_data.groupby('category')

In [54]:
#sumamos runtimes
suma_grupo = agrupacion.sum(numeric_only=True)

In [55]:
suma_grupo

,rank,hours_viewed_first_91_days,runtime,views_first_91_days,horas_por_vista,conversion_horas_a_dias
category,,,,,,
Films (English),54,2677400000,18.4000,1306300000,18.399731,1.115583e+08
Films (Non-English),55,1232900000,18.8500,663400000,18.849363,5.137083e+07
TV (English),55,9770500000,82.3334,1185600000,82.326717,4.071042e+08
TV (Non-English),55,6643000000,68.8333,933100000,68.836409,2.767917e+08

In [57]:
media_grupo = agrupacion.mean(numeric_only = True)

In [58]:
media_grupo

,rank,hours_viewed_first_91_days,runtime,views_first_91_days,horas_por_vista,conversion_horas_a_dias
category,,,,,,
Films (English),6.0,2.974889e+08,2.044444,1.451444e+08,2.044415,1.239537e+07
Films (Non-English),5.5,1.232900e+08,1.885000,6.634000e+07,1.884936,5.137083e+06
TV (English),5.5,9.770500e+08,8.233340,1.185600e+08,8.232672,4.071042e+07
TV (Non-English),5.5,6.643000e+08,6.883330,9.331000e+07,6.883641,2.767917e+07

In [59]:
conteo_agrupado = agrupacion.count()

In [60]:
conteo_agrupado

,rank,show_title,season_title,hours_viewed_first_91_days,runtime,views_first_91_days,horas_por_vista,conversion_horas_a_dias
category,,,,,,,,
Films (English),9,9,0,9,9,9,9,9
Films (Non-English),10,10,0,10,10,10,10,10
TV (English),10,10,9,10,10,10,10,10
TV (Non-English),10,10,10,10,10,10,10,10

In [61]:
horas_visualizacion_por_categoria = copia_data.groupby('category')['runtime'].sum()

In [62]:
horas_visualizacion_por_categoria

category
Films (English)        18.4000
Films (Non-English)    18.8500
TV (English)           82.3334
TV (Non-English)       68.8333
Name: runtime, dtype: float64

In [67]:
grupos_filtrados = copia_data.groupby('category').filter(lambda x: x['runtime'].sum() > 20)

In [68]:
grupos_filtrados

,category,rank,show_title,season_title,hours_viewed_first_91_days,runtime,views_first_91_days,horas_por_vista,conversion_horas_a_dias
20,TV (English),1,Wednesday,Wednesday: Season 1,1718800000,6.8167,252100000,6.817929,7.161667e+07
21,TV (English),2,Stranger Things,Stranger Things 4,1838000000,13.0667,140700000,13.063255,7.658333e+07
22,TV (English),3,DAHMER,DAHMER: Monster: The Jeffrey Dahmer Story,1031100000,8.9167,115600000,8.919550,4.296250e+07
23,TV (English),4,Bridgerton,Bridgerton: Season 1,929300000,8.2000,113300000,8.202118,3.872083e+07
24,TV (English),5,The Queen's Gambit,The Queen's Gambit: Limited Series,746400000,6.6167,112800000,6.617021,3.110000e+07
25,TV (English),6,The Night Agent,The Night Agent: Season 1,803200000,8.1833,98200000,8.179226,3.346667e+07
26,TV (English),7,Stranger Things,Stranger Things 3,716100000,7.5500,94800000,7.553797,2.983750e+07
27,TV (English),8,Bridgerton,Bridgerton: Season 2,797200000,8.5000,93800000,8.498934,3.321667e+07
28,TV (English),9,The Witcher,The Witcher: Season 1,663600000,8.0000,83000000,7.995181,2.765000e+07
29,TV (English),10,Queen Charlotte: A Bridgerton Story,NaN,526800000,6.4833,81300000,6.479705,2.195000e+07
30,TV (Non-English),1,Squid Game,Squid Game: Season 1,2205200000,8.3167,265200000,8.315234,9.188333e+07
31,TV (Non-English),2,Money Heist,Money Heist: Part 4,710200000,6.7000,106000000,6.700000,2.959167e+07
32,TV (Non-English),3,Lupin,Lupin: Part 1,396300000,3.9833,99500000,3.982915,1.651250e+07
33,TV (Non-English),4,Money Heist,Money Heist: Part 5,900700000,9.0833,99200000,9.079637,3.752917e+07
34,TV (Non-English),5,Money Heist,Money Heist: Part 3,519800000,6.5000,80000000,6.497500,2.165833e+07
35,TV (Non-English),6,Lupin,Lupin: Part 2,258900000,3.7833,68400000,3.785088,1.078750e+07
36,TV (Non-English),7,Who Killed Sara?,Who Killed Sara?: Season 1,392400000,6.7167,58400000,6.719178,1.635000e+07
37,TV (Non-English),8,All of Us Are Dead,All of Us Are Dead: Season 1,679300000,12.2333,55500000,12.239640,2.830417e+07
38,TV (Non-English),9,Dear Child,Dear Child: Limited Series,245400000,4.8167,50900000,4.821218,1.022500e+07
39,TV (Non-English),10,Elite,Elite: Season 3,334800000,6.7000,50000000,6.696000,1.395000e+07